global:
  scrape_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'spring-boot-app'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['172.17.0.1:8080'] # ip addr show docker0 -> Docker Host IP address