### Datasource
spring.datasource:
  url: jdbc:postgresql://localhost/db
  username: postgres
  password: local_pwd
  driver-class-name: org.postgresql.Driver

### ACTUATOR - INFO
info.app:
  name: @project.name@
  environment: local
  version: @project.version@

